### ISSUE TITLE
Feature request: auto check update for latest version, download and update the binaries

### ISSUE THREAD

**Issue by duytrung** [vim/vim-win32-installer#212]
Hello,

I found VS code insider has a function to check the update but not do that automatically.

Is there any way to have vim update that way? Auto check the latest version, download and install the update automatically some ways?

Thanks for considering the request

**Comment by k-takata** [comment]
There are no official ways.
If you use Chocolatey or some other third party's package manager, it may automatically do that.

**Comment by chrisbra** [comment]
Microsoft seems to settle for winget as the official packager for Windows. With #206 this repository provides a yaml file, that can be used to update the package for winget (see e.g. here: https://github.com/microsoft/winget-pkgs/pull/8721). It looks like people are already making use of updating the vim package see, e.g. https://github.com/microsoft/winget-pkgs/tree/master/manifests/vim/vim but this is currently a manual process.

Automatically updating the winget packages does not seem to be currently possible see https://github.com/microsoft/winget-pkgs/issues/2399

Once this is done, we can think about providing means to update automatically. 

And then there we should also think about automatically create the signed builds, which I currently do manually. SignPath provides API hooks to automate this, but it looks like I have to redo the setup of the  complete process, because all the authentication tokens are nowhere stored :/

So to make a long story short, use winget or chocolatey.
