### ISSUE TITLE
It won't working in remote terminal

### ISSUE THREAD

**Issue by OsmondGao** [vim/vim-win32-installer#218]
I have installed gvim_8.2.3154_x64 on winServer without error. Now I telnet my winServer in terminal and after I type vim in commandline,the cursor stop the first line whatever I input.But it works well when I login by remote desktop.

It can't accept anything even the colon at the remote terminal.

**Comment by k-takata** [comment]
Does it work when you execute with `vim --clean`?

**Comment by OsmondGao** [comment]
no,alway top-left

**Comment by OsmondGao** [comment]
This problem is also exist in 8.2.3159_x64

**Comment by OsmondGao** [comment]
I installed vim(gvim_8.2.3159_x64) on WinServer.

Then I use telnet clinet(Microsoft's) to login WinServer.

After login success,I type vim to edit some text file(command line mode),but the cursor stay the top-left and never move whatever I pressed the keyboard(including _i_ or _:_).

Anyone know how to resolve it?

**Comment by k-takata** [comment]
Which version of Windows do you use?
I think that the recent version of Windows doesn't have the telnet server. Does it work when you use the OpenSSH server instead of it?
Does it work when you use older versions of Vim? (E.g. 8.1, 8.0, or 7.4) (See https://github.com/vim/vim-win32-installer/wiki/List-of-Releases)
Is the issue only the cursor position?

**Comment by OsmondGao** [comment]
WinVersion:Windows Server 2008 R2 Enterprise
I tried v7.4.1185,but still not worked.

**Comment by OsmondGao** [comment]
Ok,I resolve it by Nano
