### ISSUE TITLE
bug of commandline "--remote-tab-silent +/pat"

### ISSUE THREAD

**Issue by hyaray** [vim/vim-win32-installer#240]
commandline `gvim.exe --remote-tab-silent +/1 c:\1.txt`
show error: `E486:Pattern not found:1|cal foreground()|if &im|star|en|redr|f`

`gvim.exe --remote-tab-silent +/1\ c:\1.txt` worked, but it's not perfect.

**Comment by chrisbra** [comment]
you may need to quote it. And possibly use `/` instead of `\`

**Comment by hyaray** [comment]
> you may need to quote it. And possibly use `/` instead of `\`

`/` is better, thanks!!
`gvim.exe --remote-tab-silent "+/1" c:\1.txt` show the same error
Is it a bug?? will it be fixed?

**Comment by k-takata** [comment]
This is caused by this line:
https://github.com/vim/vim/blob/5703310e640c4b142a16a3ea4f45317565ae8c32/src/clientserver.c#L662

The commands `|cal foreground()|if &im|star|en|redr|f` is added after the search command `/1`, then the whole string is parsed as a pattern.
A workaround is using the `exec` command:

```
gvim.exe --remote-tab-silent "+exec '/1'" c:\1.txt
```

It might be better to discuss in the [main repository](https://github.com/vim/vim/issues), not here.
