### ISSUE TITLE
VirusTotal reports that installers contain trojans

### ISSUE THREAD

**Issue by sovetov** [vim/vim-win32-installer#301]
### Steps to reproduce

Submit any of installers to VirusTotal:
https://www.virustotal.com/gui/file/e4b61fa8b1bc18d3c7c09c7850bc62b54ee5ae9b36aed363ebbce4dba1cfe0a3
https://www.virustotal.com/gui/file/8a24e87f087cb6e4d95fc85c8ba2e3e7edc1c4b6cbbe543b81b784be87f81f89
https://www.virustotal.com/gui/file/15f2263c0cb2d0b21255334eed022b9f1fe9ef7488ea800123ed4eeb2323349f

### Expected behaviour

No malicious software found.

### Version of Vim

9.0.1294

### Environment

x86 and x64 installers of this and previous versions.

**Comment by chrisbra** [comment]
I don't know why this happens. I just checked latest version and they seem to be fine now again:
- https://www.virustotal.com/gui/url/abc5b32194a93400f148a57b55511de33dd16d12cfd5ed980b34e67af5ee1b65?nocache=1
- https://www.virustotal.com/gui/url/401eea2af674bc6ac6e3db186d51bf5d7a5ebf2c55b7272d945dcf331c056968?nocache=1
- https://www.virustotal.com/gui/url/f936e86394a0c67e93ba2e83eda18bd9b137e32617e183ea26fc2c3e9d5192c1?nocache=1
- https://www.virustotal.com/gui/url/ee3d130cf32ce94e65d3e9436b11546a7454bacaddfe5ae05f5f8bd7d39dc43f?nocache=1

I suppose some issue with some of those vendors.

**Comment by sovetov** [comment]
It seems that VirusTotal shows different results for a URL and an uploaded file. URL is always "green". Try to download an installer (x86 gets more reports) and upload it to VirusTotal.

**Comment by chrisbra** [comment]
I tried again with 9.0.1313. Even firefox did not want me to download the `x86` installer, because "this file is only downloaded seldomly" :/ 
But even for the x86 installer, it is only 6 out of several vendors that complain.

In the end you would need to bug those AV vendors to find out why they flag it. Most of the report have "generic" or "heuristics" in its detection, which indicates, that this is no real threat but rather too aggressive heuristics I would guess:

For the record: I uploaded version 9.0.1313:
- https://www.virustotal.com/gui/file/cf5cf0a5fe2910b3efc0c9e35011d8d1a95cd10bcac961ad96e4ee27d081c85b
- https://www.virustotal.com/gui/file/f6619fc65adf3eafb67e7ea732548f6f74e7dc5403388ada14110d9ef17ceda7
- https://www.virustotal.com/gui/file/c2610249b273c3544ada1daff85ca2d524d6a18f713471a628a60d8263da0810
- https://www.virustotal.com/gui/file/e80b4c31300feff7068f9d8a042ee8f6f5fa742764317eaf0f34bb840b8cfcc0

**Comment by sovetov** [comment]
Thank you for verification and understanding. I created an issues mostly to have a record that this happened. It seems there's not much that could be done as a "fix" for this. Hence, I'm closing the issue.

Regarding the "generic" character of reports, I totally agree with you. Moreover, Vim 8.2 from 2018 has one "generic" report too.

But security is not something I'd take lightmindedly. Otherwise, I wouldn't bother with VirusTotal :)

**Comment by chrisbra** [comment]
yes understood and thanks for that.
